const mongoose = require("mongoose");
const Category = require("../models/Category");

const catData = [
  {
    _id: "phones-and-gadgets",
    name: "Смартфоны и гаджеты",
  },
  {
    _id: "laptops-and-pc",
    name: "Ноутбуки и компьютеры",
  },
  {
    _id: "phone",
    name: "Смартфоны",
    type: "phone",
    categoryId: "phones-and-gadgets",
    filters: [
      {
        _id: "phone-apple",
        name: "Смартфоны Apple",
        filters: [{ name: "os", value: ["iOS"] }],
      },
    ],
    img: "/img/phone-cat.jpg",
  },
  {
    _id: "tablet",
    name: "Планшеты",
    type: "tablet",
    categoryId: "phones-and-gadgets",
    img: "/img/tablet-cat.jpg",
  },
  {
    _id: "charger",
    name: "Зарядные устройства",
    type: "charger",
    categoryId: "phones-and-gadgets",
    img: "/img/charger-cat.jpg",
  },
  {
    _id: "laptop",
    name: "Ноутбуки",
    type: "laptop",
    categoryId: "laptops-and-pc",
    img: "/img/laptop-cat.jpg",
  },
  {
    _id: "pc",
    name: "Компьютеры",
    type: "pc",
    categoryId: "laptops-and-pc",
    img: "/img/pc-cat.jpg",
  },
  {
    _id: "monitor",
    name: "Мониторы",
    type: "monitor",
    categoryId: "laptops-and-pc",
    img: "/img/monitor-cat.jpg",
  },
];

const productData = [
  {
    _id: 1,
    name: "Samsung Galaxy S20",
    categoryId: "phone",
    img: "/img/phone.jpg",
    type: "phone",
    cost: 106990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 2,
    name: "Apple iPhone 13",
    categoryId: "phone",
    img: "/img/phone.jpg",
    type: "phone",
    cost: 119990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 3,
    name: "Xiaomi 11X",
    categoryId: "phone",
    img: "/img/phone.jpg",
    type: "phone",
    cost: 84990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 4,
    name: "DEXP P200",
    categoryId: "tablet",
    img: "/img/phone.jpg",
    type: "tablet",
    cost: 16790,
    stock: 10,
    orders: 0,
  },
  {
    _id: 5,
    name: "Apple iPad (2018)",
    categoryId: "tablet",
    img: "/img/phone.jpg",
    type: "tablet",
    cost: 35990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 6,
    name: "Samsung Galaxy Tab S8",
    categoryId: "tablet",
    img: "/img/phone.jpg",
    type: "tablet",
    cost: 78990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 7,
    name: "Сетевое зарядное устройство Xiaomi Mi 65W",
    categoryId: "charger",
    img: "/img/phone.jpg",
    type: "charger",
    cost: 3190,
    stock: 10,
    orders: 0,
  },
  {
    _id: 8,
    name: "Сетевое зарядное устройство Buro TJ-248W QC 3.0",
    categoryId: "charger",
    img: "/img/phone.jpg",
    type: "charger",
    cost: 490,
    stock: 10,
    orders: 0,
  },
  {
    _id: 9,
    name: "Сетевое зарядное устройство Digma DGPD-18W-WG",
    categoryId: "charger",
    img: "https://cdn.citilink.ru/oemLM_Gj5K3o70kOgFUD0XPz7rUrfQYIltyjHDYH_lA/fit/400/400/ce/false/plain/items/1079233_v01_m.jpg",
    type: "charger",
    cost: 1000,
    stock: 10,
    orders: 0,
  },
  {
    _id: 10,
    name: "Huawei MateBook D 15, 53012KQY",
    categoryId: "laptop",
    img: "/img/phone.jpg",
    type: "laptop",
    cost: 48990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 11,
    name: "Lenovo IP Gaming 3 15ACH6, 82K201D1RK",
    categoryId: "laptop",
    img: "/img/phone.jpg",
    type: "laptop",
    cost: 83990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 12,
    name: "Acer Aspire 3 A315-56-38MN, NX.HS5ER.00B",
    categoryId: "laptop",
    img: "/img/phone.jpg",
    type: "laptop",
    cost: 34990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 13,
    name: "MSI Trident A 11TC-2238XRU",
    categoryId: "pc",
    img: "/img/phone.jpg",
    type: "pc",
    cost: 117990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 14,
    name: "Acer Aspire XC-1660",
    categoryId: "pc",
    img: "/img/phone.jpg",
    type: "pc",
    cost: 55590,
    stock: 10,
    orders: 0,
  },
  {
    _id: 15,
    name: "iRU Home 310H5SE",
    categoryId: "pc",
    img: "/img/phone.jpg",
    type: "pc",
    cost: 36390,
    stock: 10,
    orders: 0,
  },
  {
    _id: 16,
    name: 'Acer KG282Kbmiipx 28"',
    categoryId: "monitor",
    img: "/img/phone.jpg",
    type: "monitor",
    cost: 25990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 17,
    name: 'LG UltraGear 24GN650-B 23.8"',
    categoryId: "monitor",
    img: "/img/phone.jpg",
    type: "monitor",
    cost: 20490,
    stock: 10,
    orders: 0,
  },
  {
    _id: 18,
    name: 'LG 27MK430H-B 27"',
    categoryId: "monitor",
    img: "/img/phone.jpg",
    type: "monitor",
    cost: 18990,
    stock: 10,
    orders: 0,
  },
  {
    _id: 19,
    name: "Item 19",
    categoryId: 31,
    img: "/img/phone.jpg",
    type: "tv",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 20,
    name: "Item 20",
    categoryId: 31,
    img: "/img/phone.jpg",
    type: "tv",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 21,
    name: "Item 21",
    categoryId: 31,
    img: "/img/phone.jpg",
    type: "tv",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 22,
    name: "Item 22",
    categoryId: 32,
    img: "/img/phone.jpg",
    type: "headphone",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 23,
    name: "Item 23",
    categoryId: 32,
    img: "/img/phone.jpg",
    type: "headphone",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 24,
    name: "Item 24",
    categoryId: 32,
    img: "/img/phone.jpg",
    type: "headphone",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 25,
    name: "Item 25",
    categoryId: 33,
    img: "/img/phone.jpg",
    type: "video",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 26,
    name: "Item 26",
    categoryId: 33,
    img: "/img/phone.jpg",
    type: "video",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
  {
    _id: 27,
    name: "Item 27",
    categoryId: 33,
    img: "/img/phone.jpg",
    type: "video",
    cost: 3300,
    stock: 10,
    orders: 0,
  },
];

const paramData = [
  {
    productId: 1,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 2,
    type: "phone",
    resolution: "2688 x 1242",
    os: "iOS",
    battery: "6500mAh",
  },
  {
    productId: 3,
    type: "phone",
    resolution: "1366×768",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 4,
    type: "tablet",
    processor: "Qualcomm",
    display: "IPS",
    battery: "5200mAh",
  },
  {
    productId: 5,
    type: "tablet",
    processor: "MediaTek",
    display: "AMOLED",
    battery: "7000mAh",
  },
  {
    productId: 6,
    type: "tablet",
    processor: "Exynos",
    display: "Dynamic AMOLED",
    battery: "4800mAh",
  },
  {
    productId: 7,
    type: "charger",
    chargerType: "Сетевое з/у",
    brand: "Xiaomi",
    port: "USB-C",
  },
  {
    productId: 8,
    type: "charger",
    chargerType: "Сетевое з/у",
    brand: "Buro",
    port: "MicroUSB",
  },
  {
    productId: 9,
    type: "charger",
    chargerType: "Сетевое з/у",
    brand: "Digma",
    port: "USB-C",
  },
  {
    productId: 10,
    type: "laptop",
    laptopType: "Ноутбук",
    screenSize: '16.1"',
    processor: "Core i7",
  },
  {
    productId: 11,
    type: "laptop",
    laptopType: "Трансформер",
    screenSize: '13.3"',
    processor: "Core i5",
  },
  {
    productId: 12,
    type: "laptop",
    laptopType: "Ультрабук",
    screenSize: '13.3"',
    processor: "Core i5",
  },
  {
    productId: 13,
    type: "pc",
    processor: "Core i7",
    graphics: "AMD Radeon R7",
    os: "Windows 10",
  },
  {
    productId: 14,
    type: "pc",
    processor: "Core i5",
    graphics: "NVIDIA GeForce RTX 3060",
    os: "Windows 11",
  },
  {
    productId: 15,
    type: "pc",
    processor: "Core i7",
    graphics: "Intel UHD Graphics 750",
    os: "No OS",
  },
  {
    productId: 16,
    type: "monitor",
    resolution: "2560 x 1440",
    screenSize: '28"',
    matrix: "OLED",
  },
  {
    productId: 17,
    type: "monitor",
    resolution: "2560 x 1440",
    screenSize: '23.8"',
    matrix: "IPS",
  },
  {
    productId: 18,
    type: "monitor",
    resolution: "1920 x 800",
    screenSize: '27"',
    matrix: "IPS",
  },
  {
    productId: 19,
    type: "phone",
    resolution: "1920 x 800",
    os: "iOS",
    battery: "3600mAh",
  },
  {
    productId: 20,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 21,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 22,
    type: "phone",
    resolution: "1920 x 800",
    os: "iOS",
    battery: "4500mAh",
  },
  {
    productId: 23,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 24,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 25,
    type: "phone",
    resolution: "1920 x 800",
    os: "iOS",
    battery: "4500mAh",
  },
  {
    productId: 26,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
  {
    productId: 27,
    type: "phone",
    resolution: "1920 x 800",
    os: "Android",
    battery: "4500mAh",
  },
];

module.exports = async () => {
  try {
    Category.deleteMany({}, () => console.log("cats cleared"));

    catData.map(async (cat) => {
      const category = await Category.create(cat);
    });
  } catch (error) {
    console.error(error);
  }
};
